#!/usr/bin/env python3
"""Generate compose.custom.yml from config/settings.yaml converter plugin config.

Reads which converter sub-converters are enabled and writes a compose override
that bakes only the required Python extras into the image.

Usage:
    make generate-compose
    # then: make docker-build-custom  OR  make docker-rebuild-custom
"""

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("pyyaml not found — run: pip install pyyaml  or use .venv/bin/python")
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
SETTINGS_PATH = ROOT / "config" / "settings.yaml"
OUTPUT_PATH = ROOT / "compose.custom.yml"

# Sub-converter → Python packages required at image build time.
# Only packages that are NOT in requirements.lock belong here.
_SUBCONVERTER_EXTRAS: dict[str, list[str]] = {
    "web":    ["youtube_transcript_api>=1.0.0,<2"],
    "office": ["mammoth", "openpyxl", "python-pptx"],
    "pdf":    ["pdfplumber"],
    "misc":   [],  # base markitdown handles these — no extras needed
}


def main() -> None:
    if not SETTINGS_PATH.exists():
        print(f"Error: {SETTINGS_PATH} not found.")
        print("Copy config/settings.yaml.example to config/settings.yaml first.")
        sys.exit(1)

    with open(SETTINGS_PATH, encoding="utf-8") as f:
        settings = yaml.safe_load(f) or {}

    plugins = settings.get("plugins", {})
    converter = plugins.get("converter", {})
    converter_enabled = converter.get("enabled", True)

    extras: list[str] = []
    enabled_subs: list[str] = []
    disabled_subs: list[str] = []

    for sub, packages in _SUBCONVERTER_EXTRAS.items():
        if not packages:
            continue
        if converter_enabled and converter.get(f"{sub}_enabled", True):
            extras.extend(packages)
            enabled_subs.append(sub)
        else:
            disabled_subs.append(sub)

    extras_str = " ".join(extras)

    compose: dict = {
        "services": {
            "markdownkb": {
                "build": {
                    "context": ".",
                    "args": {"EXTRAS": extras_str},
                }
            },
            "markdownkb-mcp": {
                "build": {
                    "context": ".",
                    "args": {"EXTRAS": extras_str},
                }
            },
        }
    }

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/generate_compose.py — do not edit by hand.\n")
        f.write("# Regenerate with: make generate-compose\n")
        f.write("# Build with:      make docker-build-custom\n\n")
        yaml.dump(compose, f, default_flow_style=False, allow_unicode=True)

    print(f"Generated {OUTPUT_PATH.name}")
    if extras_str:
        print(f"  EXTRAS: {extras_str}")
        print(f"  Sub-converters included: {', '.join(enabled_subs)}")
    else:
        print("  EXTRAS: (none — converter disabled or all sub-converters off)")
    if disabled_subs:
        print(f"  Sub-converters excluded: {', '.join(disabled_subs)}")
    print()
    print("  Next steps:")
    print("    make docker-build-custom    # cached build")
    print("    make docker-rebuild-custom  # clean build (after dep changes)")


if __name__ == "__main__":
    main()
